version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    allow:
      - dependency-name: "etos-lib"
    groups:
      etos-lib:
        patterns:
          - "etos-lib"
